package com.takeruf.nagi.ui.localization

import android.content.Context
import androidx.annotation.StringRes
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.platform.LocalConfiguration
import androidx.compose.ui.platform.LocalContext
import com.takeruf.nagi.R
import com.takeruf.nagi.domain.model.BrowserTab
import com.takeruf.nagi.domain.model.Space

/** Capture in composition so callbacks and semantics use the same localized resources. */
@Composable
fun rememberNagiStrings(): NagiStrings {
    val context = LocalContext.current
    val configuration = LocalConfiguration.current
    return remember(context, configuration) { NagiStrings(context) }
}

class NagiStrings(private val context: Context) {
    operator fun invoke(@StringRes id: Int, vararg args: Any): String = if (args.isEmpty()) context.getString(id) else context.getString(id, *args)
    fun tabTitle(tab: BrowserTab): String = if (tab.url == "about:blank") invoke(R.string.ui_new_tab) else tab.title
    fun spaceName(space: Space): String = when {
        space.id == "personal" && space.name == "Personal" -> invoke(R.string.ui_personal)
        space.id == "work" && space.name == "Work" -> invoke(R.string.ui_work)
        else -> space.name
    }
    // Domain validation messages and command labels remain platform-independent.
    fun translate(english: String): String = when (english) {
        "New tab" -> invoke(R.string.ui_new_tab)
        "Search" -> invoke(R.string.ui_search)
        "History" -> invoke(R.string.ui_history)
        "Bookmarks" -> invoke(R.string.ui_bookmarks)
        "Settings" -> invoke(R.string.ui_settings)
        "Space" -> invoke(R.string.ui_space)
        "Spaces" -> invoke(R.string.ui_spaces)
        "Personal" -> invoke(R.string.ui_personal)
        "Work" -> invoke(R.string.ui_work)
        "Save" -> invoke(R.string.ui_save)
        "Cancel" -> invoke(R.string.ui_cancel)
        "Delete" -> invoke(R.string.ui_delete)
        "Back" -> invoke(R.string.ui_back)
        "Forward" -> invoke(R.string.ui_forward)
        "Reload" -> invoke(R.string.ui_reload)
        "Back to browser" -> invoke(R.string.ui_back_to_browser)
        "Expand sidebar" -> invoke(R.string.ui_expand_sidebar)
        "Collapse sidebar" -> invoke(R.string.ui_collapse_sidebar)
        "Search or enter URL" -> invoke(R.string.ui_search_or_enter_url)
        "New tab home" -> invoke(R.string.ui_new_tab_home)
        "Search anything" -> invoke(R.string.ui_search_anything)
        "Drop to favorite" -> invoke(R.string.ui_drop_to_favorite)
        "Drag a tab here to favorite" -> invoke(R.string.ui_drag_a_tab_here_to_favorite)
        "Sidebar tabs" -> invoke(R.string.ui_sidebar_tabs)
        "Toggle pinned tabs" -> invoke(R.string.ui_toggle_pinned_tabs)
        "Space actions" -> invoke(R.string.ui_space_actions)
        "New Space" -> invoke(R.string.ui_new_space)
        "Edit Space" -> invoke(R.string.ui_edit_space)
        "Delete Space" -> invoke(R.string.ui_delete_space)
        "Drop to pin" -> invoke(R.string.ui_drop_to_pin)
        "Keep your everyday tabs here" -> invoke(R.string.ui_keep_your_everyday_tabs_here)
        "Drop as an unpinned tab" -> invoke(R.string.ui_drop_as_an_unpinned_tab)
        "Release to favorite" -> invoke(R.string.ui_release_to_favorite)
        "Release to pin" -> invoke(R.string.ui_release_to_pin)
        "Release to open in Space" -> invoke(R.string.ui_release_to_open_in_space)
        "Release to move to Space" -> invoke(R.string.ui_release_to_move_to_space)
        "Release to place tab" -> invoke(R.string.ui_release_to_place_tab)
        "Drag to arrange your sidebar" -> invoke(R.string.ui_drag_to_arrange_your_sidebar)
        "Space name" -> invoke(R.string.ui_space_name)
        "Emoji or custom icon" -> invoke(R.string.ui_emoji_or_custom_icon)
        "Icon" -> invoke(R.string.ui_icon)
        "Theme" -> invoke(R.string.ui_theme)
        "Its tabs will be removed. Shared favorites stay available." -> invoke(R.string.ui_its_tabs_will_be_removed_shared_favorites_stay_available)
        "Show actions" -> invoke(R.string.ui_show_actions)
        "Remove favorite" -> invoke(R.string.ui_remove_favorite)
        "Unpin tab" -> invoke(R.string.ui_unpin_tab)
        "Pin tab" -> invoke(R.string.ui_pin_tab)
        "Add to favorites" -> invoke(R.string.ui_add_to_favorites)
        "Save bookmark" -> invoke(R.string.ui_save_bookmark)
        "Open in right pane" -> invoke(R.string.ui_open_in_right_pane)
        "Close tab" -> invoke(R.string.ui_close_tab)
        "Make it yours" -> invoke(R.string.ui_make_it_yours)
        "A browser that fits your workspace." -> invoke(R.string.ui_a_browser_that_fits_your_workspace)
        "General" -> invoke(R.string.ui_general)
        "Default search engine" -> invoke(R.string.ui_default_search_engine)
        "Select" -> invoke(R.string.ui_select)
        "Automatic search by region" -> invoke(R.string.ui_automatic_search_by_region)
        "Mainland China: 百度 · elsewhere: Google. Choosing an engine turns this off." -> invoke(R.string.ui_mainland_china_elsewhere_google_choosing_an_engine_turns_this_off)
        "Region unavailable · current engine kept" -> invoke(R.string.ui_region_unavailable_current_engine_kept)
        "Detecting region…" -> invoke(R.string.ui_detecting_region)
        "Check again" -> invoke(R.string.ui_check_again)
        "Open links in new tab" -> invoke(R.string.ui_open_links_in_new_tab)
        "Page links you tap open as a new tab" -> invoke(R.string.ui_page_links_you_tap_open_as_a_new_tab)
        "Restore tabs on launch" -> invoke(R.string.ui_restore_tabs_on_launch)
        "Keep your Spaces and open tabs between sessions" -> invoke(R.string.ui_keep_your_spaces_and_open_tabs_between_sessions)
        "Desktop site by default" -> invoke(R.string.ui_desktop_site_by_default)
        "Use a desktop user agent for newly created sessions" -> invoke(R.string.ui_use_a_desktop_user_agent_for_newly_created_sessions)
        "Search engines" -> invoke(R.string.ui_search_engines)
        "  Default" -> invoke(R.string.ui_default)
        "Add search engine" -> invoke(R.string.ui_add_search_engine)
        "Appearance" -> invoke(R.string.ui_appearance)
        "Theme color" -> invoke(R.string.ui_theme_color)
        "Forest" -> invoke(R.string.ui_forest)
        "Blue" -> invoke(R.string.ui_blue)
        "Purple" -> invoke(R.string.ui_purple)
        "Rose" -> invoke(R.string.ui_rose)
        "Orange" -> invoke(R.string.ui_orange)
        "Slate" -> invoke(R.string.ui_slate)
        "Sidebar width" -> invoke(R.string.ui_sidebar_width)
        "Collapsed" -> invoke(R.string.ui_collapsed)
        "At the minimum width, the sidebar folds into a rail." -> invoke(R.string.ui_at_the_minimum_width_the_sidebar_folds_into_a_rail)
        "You can also drag the sidebar edge." -> invoke(R.string.ui_you_can_also_drag_the_sidebar_edge)
        "Tabs" -> invoke(R.string.ui_tabs)
        "Restore a closed tab" -> invoke(R.string.ui_restore_a_closed_tab)
        "Restore" -> invoke(R.string.ui_restore)
        "Archive inactive tabs" -> invoke(R.string.ui_archive_inactive_tabs)
        "Checked on launch or when you choose Archive now. Pinned and selected tabs are kept." -> invoke(R.string.ui_checked_on_launch_or_when_you_choose_archive_now_pinned_b64b52e0)
        "Never" -> invoke(R.string.ui_never)
        "24 hours" -> invoke(R.string.ui_24_hours)
        "7 days" -> invoke(R.string.ui_7_days)
        "30 days" -> invoke(R.string.ui_30_days)
        "Archive now" -> invoke(R.string.ui_archive_now)
        "Privacy" -> invoke(R.string.ui_privacy)
        "Automatic search uses api.country.is to resolve the connection country. It sees your IP, but receives no search or browsing history. If unavailable, mobile network, SIM, then device region are used. A VPN can change the detected country. Turn off Automatic search by region to stop lookups." -> invoke(R.string.ui_automatic_search_uses_api_country_is_to_resolve_the_con_012b7a40)
        "Your workspace stays on this device." -> invoke(R.string.ui_your_workspace_stays_on_this_device)
        "History, tabs and bookmarks are stored locally. Sites ask before accessing your camera, microphone or location. Third-party cookies are blocked." -> invoke(R.string.ui_history_tabs_and_bookmarks_are_stored_locally_sites_ask_5d51ee23)
        "Clear browsing history" -> invoke(R.string.ui_clear_browsing_history_a2d6ed)
        "Private browsing and content blocking are planned for a later release." -> invoke(R.string.ui_private_browsing_and_content_blocking_are_planned_for_a_later_release)
        "Nagi 0.1.0  ·  Made for a little more room." -> invoke(R.string.ui_nagi_0_1_0_made_for_a_little_more_room)
        "Clear browsing history?" -> invoke(R.string.ui_clear_browsing_history_199567)
        "This removes saved visits from this device." -> invoke(R.string.ui_this_removes_saved_visits_from_this_device)
        "Clear history" -> invoke(R.string.ui_clear_history)
        "Edit search engine" -> invoke(R.string.ui_edit_search_engine)
        "Name" -> invoke(R.string.ui_name)
        "Keyword" -> invoke(R.string.ui_keyword)
        "Search URL Template" -> invoke(R.string.ui_search_url_template)
        "Use {query} where the search text belongs" -> invoke(R.string.ui_use_query_where_the_search_text_belongs)
        "Icon URL (optional)" -> invoke(R.string.ui_icon_url_optional)
        "That keyword is already in use" -> invoke(R.string.ui_that_keyword_is_already_in_use)
        "Custom theme color" -> invoke(R.string.ui_custom_theme_color)
        "HEX color" -> invoke(R.string.ui_hex_color)
        "Six hexadecimal digits, for example #3568C0" -> invoke(R.string.ui_six_hexadecimal_digits_for_example_3568c0)
        "Resize split view" -> invoke(R.string.ui_resize_split_view)
        "Your browsing history will appear here." -> invoke(R.string.ui_your_browsing_history_will_appear_here)
        "Save pages from the page menu. Favorites live in your sidebar." -> invoke(R.string.ui_save_pages_from_the_page_menu_favorites_live_in_your_sidebar)
        "Search history" -> invoke(R.string.ui_search_history)
        "Search bookmarks" -> invoke(R.string.ui_search_bookmarks)
        "Page menu" -> invoke(R.string.ui_page_menu)
        "Unpin from sidebar" -> invoke(R.string.ui_unpin_from_sidebar)
        "Pin to sidebar" -> invoke(R.string.ui_pin_to_sidebar)
        "Use mobile site" -> invoke(R.string.ui_use_mobile_site)
        "Use desktop site" -> invoke(R.string.ui_use_desktop_site)
        "Find in page" -> invoke(R.string.ui_find_in_page)
        "New split view" -> invoke(R.string.ui_new_split_view)
        "Swap panes" -> invoke(R.string.ui_swap_panes)
        "Close split view" -> invoke(R.string.ui_close_split_view)
        "Choose tab" -> invoke(R.string.ui_choose_tab)
        "your Space" -> invoke(R.string.ui_your_space)
        "Retry" -> invoke(R.string.ui_retry)
        "Previous match" -> invoke(R.string.ui_previous_match)
        "Next match" -> invoke(R.string.ui_next_match)
        "Close find" -> invoke(R.string.ui_close_find)
        "Where would you like to go?" -> invoke(R.string.ui_where_would_you_like_to_go)
        "Could not open workspace" -> invoke(R.string.ui_could_not_open_workspace)
        "Action could not be completed" -> invoke(R.string.ui_action_could_not_be_completed)
        "No closed tabs to restore" -> invoke(R.string.ui_no_closed_tabs_to_restore)
        "Search, enter a URL, or type > for commands" -> invoke(R.string.ui_search_enter_a_url_or_type_for_commands)
        "Ready" -> invoke(R.string.ui_ready)
        "Composing" -> invoke(R.string.ui_composing)
        "No matches" -> invoke(R.string.ui_no_matches)
        "↑ ↓  Navigate     ↵  Open     g · ddg · yt · gh · scholar  Keyword search" -> invoke(R.string.ui_navigate_open_g_ddg_yt_gh_scholar_keyword_search)
        "Exit fullscreen" -> invoke(R.string.ui_exit_fullscreen)
        "Open tabs" -> invoke(R.string.ui_open_tabs)
        "Commands" -> invoke(R.string.ui_commands)
        "Two panes" -> invoke(R.string.ui_two_panes)
        "One pane" -> invoke(R.string.ui_one_pane)
        "Restore closed tab" -> invoke(R.string.ui_restore_closed_tab)
        "Toggle sidebar" -> invoke(R.string.ui_toggle_sidebar)
        "More room" -> invoke(R.string.ui_more_room)
        "Open settings" -> invoke(R.string.ui_open_settings)
        "Preferences" -> invoke(R.string.ui_preferences)
        "Open history" -> invoke(R.string.ui_open_history)
        "Recent visits" -> invoke(R.string.ui_recent_visits)
        "Open bookmarks" -> invoke(R.string.ui_open_bookmarks)
        "Saved pages" -> invoke(R.string.ui_saved_pages)
        "Toggle desktop site" -> invoke(R.string.ui_toggle_desktop_site)
        "User agent" -> invoke(R.string.ui_user_agent)
        "Website" -> invoke(R.string.ui_website)
        "System" -> invoke(R.string.ui_system)
        "Light" -> invoke(R.string.ui_light)
        "Dark" -> invoke(R.string.ui_dark)
        "Mobile network" -> invoke(R.string.ui_mobile_network)
        "Device region" -> invoke(R.string.ui_device_region)
        "Unavailable" -> invoke(R.string.ui_unavailable)
        "Name is required" -> invoke(R.string.ui_name_is_required)
        "Keyword must use lowercase letters, numbers, - or _" -> invoke(R.string.ui_keyword_must_use_lowercase_letters_numbers_or)
        "Search URL must contain {query}" -> invoke(R.string.ui_search_url_must_contain_query)
        "Use a valid https search URL" -> invoke(R.string.ui_use_a_valid_https_search_url)
        "Icon URL is invalid" -> invoke(R.string.ui_icon_url_is_invalid)
        "Keep at least one search engine" -> invoke(R.string.ui_keep_at_least_one_search_engine)
        "Keep up to 12 favorites" -> invoke(R.string.ui_keep_up_to_12_favorites)
        "Space name is required" -> invoke(R.string.ui_space_name_is_required)
        "Keep at least one Space" -> invoke(R.string.ui_keep_at_least_one_space)
        "Space no longer exists" -> invoke(R.string.ui_space_no_longer_exists)
        "Enter a URL or search query" -> invoke(R.string.ui_enter_a_url_or_search_query)
        "Only http and https addresses can be opened here" -> invoke(R.string.ui_only_http_and_https_addresses_can_be_opened_here)
        "Add a search engine in Settings" -> invoke(R.string.ui_add_a_search_engine_in_settings)
        "No file picker is available" -> invoke(R.string.ui_no_file_picker_is_available)
        "Allow site access?" -> invoke(R.string.ui_allow_site_access)
        "Allow" -> invoke(R.string.ui_allow)
        "Block" -> invoke(R.string.ui_block)
        "Download file?" -> invoke(R.string.ui_download_file)
        "Download" -> invoke(R.string.ui_download)
        "Download started" -> invoke(R.string.ui_download_started)
        "Open another app?" -> invoke(R.string.ui_open_another_app)
        "Open" -> invoke(R.string.ui_open)
        "No app can open this link" -> invoke(R.string.ui_no_app_can_open_this_link)
        "Camera" -> invoke(R.string.ui_camera)
        "Microphone" -> invoke(R.string.ui_microphone)
        "Location" -> invoke(R.string.ui_location)
        "Downloaded with Nagi" -> invoke(R.string.ui_downloaded_with_nagi)
        "This address type is not supported" -> invoke(R.string.ui_this_address_type_is_not_supported)
        "The site's certificate could not be verified." -> invoke(R.string.ui_the_site_s_certificate_could_not_be_verified)
        "Blank script-generated popups are not supported in this MVP" -> invoke(R.string.ui_blank_script_generated_popups_are_not_supported_in_this_mvp)
        "Blob and data downloads are not supported in this MVP" -> invoke(R.string.ui_blob_and_data_downloads_are_not_supported_in_this_mvp)
        "This popup address is not supported" -> invoke(R.string.ui_this_popup_address_is_not_supported)
        "Tab %1\$s" -> invoke(R.string.ui_tab_1_s)
        "Archived · %1\$s" -> invoke(R.string.ui_archived_1_s)
        "Switch to %1\$s" -> invoke(R.string.ui_switch_to_1_s)
        "Space icon %1\$s" -> invoke(R.string.ui_space_icon_1_s)
        "Space theme %1\$s" -> invoke(R.string.ui_space_theme_1_s)
        "Delete %1\$s?" -> invoke(R.string.ui_delete_1_s_137cdc)
        "Favorite %1\$s" -> invoke(R.string.ui_favorite_1_s)
        "Favorite actions for %1\$s" -> invoke(R.string.ui_favorite_actions_for_1_s)
        "Drag %1\$s" -> invoke(R.string.ui_drag_1_s)
        "Actions for %1\$s" -> invoke(R.string.ui_actions_for_1_s)
        "Close %1\$s" -> invoke(R.string.ui_close_1_s)
        "Move to %1\$s" -> invoke(R.string.ui_move_to_1_s)
        "Make %1\$s default" -> invoke(R.string.ui_make_1_s_default)
        "Edit %1\$s" -> invoke(R.string.ui_edit_1_s)
        "Delete %1\$s" -> invoke(R.string.ui_delete_1_s_48c860)
        "Custom color · #%1\$s" -> invoke(R.string.ui_custom_color_1_s)
        "Remove %1\$s" -> invoke(R.string.ui_remove_1_s)
        "Workspace could not be opened: %1\$s" -> invoke(R.string.ui_workspace_could_not_be_opened_1_s)
        "Open %1\$s" -> invoke(R.string.ui_open_1_s)
        "Search %1\$s for “%2\$s”" -> invoke(R.string.ui_search_1_s_for_2_s)
        "Search %1\$s" -> invoke(R.string.ui_search_1_s)
        "%1\$s wants to use your %2\$s. Access lasts for this request." -> invoke(R.string.ui_1_s_wants_to_use_your_2_s_access_lasts_for_this_request)
        "Download failed: %1\$s" -> invoke(R.string.ui_download_failed_1_s)
        else -> english
    }
}
