"""Generate the offline Lucide catalog from Android AAR resources and lucide-static SVGs.
Usage: python3 scripts/generate_lucide_catalog.py --aar PATH --svg-dir PATH
SVG source: lucide-static 1.52.0 (ISC), https://lucide.dev
"""
import argparse
from pathlib import Path
import xml.etree.ElementTree as ET
import zipfile

parser = argparse.ArgumentParser()
parser.add_argument('--aar', type=Path, required=True)
parser.add_argument('--svg-dir', type=Path, required=True)
args = parser.parse_args()
root = Path(__file__).resolve().parents[1]
with zipfile.ZipFile(args.aar) as archive:
    existing = {line.split()[2].removeprefix('lucide_ic_').replace('_', '-') : line.split()[2]
                for line in archive.read('R.txt').decode().splitlines() if line.startswith('int drawable lucide_ic_')}


def path_data(el):
    tag = el.tag.split('}')[-1]
    a = el.attrib
    if tag == 'path':
        return a['d']
    if tag == 'line':
        return f"M{a['x1']},{a['y1']} L{a['x2']},{a['y2']}"
    if tag in ('polyline', 'polygon'):
        points = a['points'].replace(',', ' ').split()
        return 'M' + ' L'.join(f'{points[i]},{points[i+1]}' for i in range(0, len(points), 2)) + (' Z' if tag == 'polygon' else '')
    if tag in ('circle', 'ellipse'):
        x, y = float(a['cx']), float(a['cy'])
        rx, ry = (float(a['r']), float(a['r'])) if tag == 'circle' else (float(a['rx']), float(a['ry']))
        return f'M{x-rx},{y} a{rx},{ry} 0 1,0 {2*rx},0 a{rx},{ry} 0 1,0 {-2*rx},0'
    if tag == 'rect':
        x, y, w, h = (float(a[k]) for k in ('x', 'y', 'width', 'height'))
        rx = min(float(a.get('rx', a.get('ry', 0))), w/2)
        ry = min(float(a.get('ry', a.get('rx', 0))), h/2)
        if not rx or not ry:
            return f'M{x},{y} h{w} v{h} h{-w} Z'
        return f'M{x+rx},{y} h{w-2*rx} a{rx},{ry} 0 0,1 {rx},{ry} v{h-2*ry} a{rx},{ry} 0 0,1 {-rx},{ry} h{-w+2*rx} a{rx},{ry} 0 0,1 {-rx},{-ry} v{-h+2*ry} a{rx},{ry} 0 0,1 {rx},{-ry} Z'
    raise ValueError(f'Unsupported SVG element: {tag}')

catalog = {name: f'LucideR.drawable.{resource}' for name, resource in existing.items()}
resource_dir = root / 'app/src/main/res/drawable'
android = 'http://schemas.android.com/apk/res/android'
ET.register_namespace('android', android)
for svg in sorted(args.svg_dir.glob('*.svg')):
    if svg.stem in existing:
        continue
    resource = 'lucide_extra_' + svg.stem.replace('-', '_')
    vector = ET.Element('vector', {f'{{{android}}}{k}': v for k, v in {
        'width':'24dp', 'height':'24dp', 'viewportWidth':'24', 'viewportHeight':'24'}.items()})
    for element in ET.fromstring(svg.read_text()):
        attributes = {'pathData': path_data(element), 'fillColor': '#FF000000' if element.get('fill') == 'currentColor' else '@android:color/transparent',
                      'strokeColor':'#FF000000', 'strokeWidth':'2', 'strokeLineCap':'round', 'strokeLineJoin':'round'}
        ET.SubElement(vector, 'path', {f'{{{android}}}{k}':v for k,v in attributes.items()})
    ET.indent(vector)
    (resource_dir / f'{resource}.xml').write_text('<!-- Lucide static 1.52.0, ISC. Generated by scripts/generate_lucide_catalog.py -->\n' + ET.tostring(vector, encoding='unicode') + '\n')
    catalog[svg.stem] = f'R.drawable.{resource}'
items = sorted(catalog.items())
chunks = [items[i:i+150] for i in range(0, len(items), 150)]
source = ['// Generated by scripts/generate_lucide_catalog.py. Do not edit by hand.',
          'package com.takeruf.nagi.ui.components', '', 'import com.takeruf.nagi.R',
          'import com.composables.icons.lucide.R as LucideR', '',
          '/** Direct resource references keep every selectable icon available in release builds. */',
          'internal object LucideIconCatalog {', '    private val resources: Map<String, Int> by lazy {', '        buildMap {']
source += [f'            putAll(part{i}())' for i in range(len(chunks))]
source += ['        }', '    }', '', '    fun resource(code: String): Int? = resources[code]', '    val names: Set<String> get() = resources.keys', '']
for i, chunk in enumerate(chunks):
    source += [f'    private fun part{i}() = mapOf('] + [f'        "{name}" to {res},' for name,res in chunk] + ['    )', '']
source += ['}', '']
(root / 'app/src/main/java/com/takeruf/nagi/ui/components/LucideIconCatalog.kt').write_text('\n'.join(source))
print(f'Generated {len(items)} selectable codes; {len(catalog)-len(existing)} supplemental vectors.')
